### ISSUE TITLE
Some feature requests 

### ISSUE THREAD

**Issue by akhater** [albertopoljak/Licensy#16]
1. way to get all active licenses info
Code username activation date and expiry date?

Maybe in a csv file it would be ideal 

2. Set license expiry based on a date would be helpful

3. Would the delete_all command affect activated licenses.?

Thank you

**Comment by albertopoljak** [comment]
1 is planned in the rewrite branch.
2 is a new idea I didn't think of before, I'l add it todo
3 it would only delete unactivated generated licenses, would not touch active ones.

**Comment by akhater** [comment]
Thank you for your quick reply

I'm facing an annoying issue, when handing out licenses to users some take time to activate them so I'm giving them again to different users by mistake 

Is it possible to let the bot deliver them directly to the end user so it can keep track of that? 

Maybe with a a custom message 

That would be dope

**Comment by albertopoljak** [comment]
There is a command that let's you manually activate license called add_license
```
!add_license <license> <member>

Manually add license to member.
```

No support for custom message, I could add it todo ig but dunno.

**Comment by akhater** [comment]
> There is a command that let's you manually activate license called add_license
> 
> ```
> !add_license <license> <member>
> 
> Manually add license to member.
> ```
> 
> No support for custom message, I could add it todo ig but dunno.

ok that would solve it.... thank you , No need for the custom message then 

thanks
