### ISSUE TITLE
Feature Request - Change Nickname

### ISSUE THREAD

**Issue by akhater** [albertopoljak/Licensy#17]
It would be cool if we can change the nickname of the bot 

thank you

**Comment by albertopoljak** [comment]
You already can, this is Discord related.

**Comment by akhater** [comment]
weird, I don't have the "Change Nickname" Option on licensy

**Comment by akhater** [comment]
ok the problem was with the Nickname hierarchy....

**Comment by albertopoljak** [comment]
Oki, closing this then.
